### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by roburst2** [allanj/LayoutLMv3-DocVQA#2]
I am trying to train on DOCVQA with layoutlmv2 and facing below error on train_dataloader loop

RuntimeError: CUDA error: device-side assert triggered

**Comment by roburst2** [comment]
@allanj When i ran this code on cpu got below error
IndexError: The `bbox` coordinate values should be within 0-1000 range.

**Comment by roburst2** [comment]
Able to resolve above error by adding box normalization before tokenization

But now i am getting **loss NaN** while training. and Constant ANLS through out training

**Comment by allanj** [comment]
Sorry for the late response. I was on sick leave for the past few days. 
Yeah, I do remember there was the problem for the bbox in LayoutLMv2, but not LayoutLMv3 because V3 handle that part automatically. 

Let me try to run again to see what's happening for V2

**Comment by allanj** [comment]
I actually just tried small data. but did get NaN loss. can you show more detail?

**Comment by allanj** [comment]
Even though I use 10k training data, full validation, I can still get a number for the loss

**Comment by roburst2** [comment]
Data created by **extract_start_end_index_v3** method i got Nan while training 
But when i created data with V1 i got the loss number.
Now the issue is ANLS is almost in same range through out the training. i got 0.61
even loss is decreasing.

Note: I am not using generator and msr

**Comment by roburst2** [comment]
Below are the logs for few epochs

Finish epoch: 16, loss: 1599.45, mean loss: 0.14
--validation: 100%|██████████| 1631/1631 [02:21<00:00, 11.49it/s]
Post-processing 5349 example predictions split into 6523 features.
prediction: ['8.28', 'university of california,', 'itc limited', 'san diego', 'mr. ms.', '1128 sixteenth st., n. w., washington, d. c. 20036', 'an asset for the nation', 'the robert a. welch foundation', '11:14 to', '15,000.00']
gold_answers: [['0.28'], ['university of california, san diego', 'university of california'], ['itc limited'], ['san diego'], ['paul'], ['1128 sixteenth st., n. w., washington, d. c. 20036'], ['aashirvaad'], ['the robert a. welch foundation'], ['11:14 to 11:39 a.m.', '11.14 to 11.39 a.m.'], ['$975.00', '975.00']]
[Info] Average Normalized Lev.S : 0.6162590623109804
Writing results to results/layoutlmv2-extractive-uncased.res.json and results/layoutlmv2-extractive-uncased.err.json
****Epoch Separation****
--training batch: 100%|██████████| 11092/11092 [52:00<00:00,  3.55it/s]
Finish epoch: 17, loss: 1493.43, mean loss: 0.13
--validation: 100%|██████████| 1631/1631 [02:22<00:00, 11.48it/s]
Post-processing 5349 example predictions split into 6523 features.
prediction: ['8.28', 'university of california,', 'itc', 'san diego', 'mr. ms.', '1128 sixteenth st., n. w., washington, d. c. 20036', 'an asset for the nation', 'the robert a. welch foundation', '11:14 to', '97500']
gold_answers: [['0.28'], ['university of california, san diego', 'university of california'], ['itc limited'], ['san diego'], ['paul'], ['1128 sixteenth st., n. w., washington, d. c. 20036'], ['aashirvaad'], ['the robert a. welch foundation'], ['11:14 to 11:39 a.m.', '11.14 to 11.39 a.m.'], ['$975.00', '975.00']]
[Info] Average Normalized Lev.S : 0.6188592941915747
Writing results to results/layoutlmv2-extractive-uncased.res.json and results/layoutlmv2-extractive-uncased.err.json
****Epoch Separation****
--training batch: 100%|██████████| 11092/11092 [52:03<00:00,  3.55it/s]
Finish epoch: 18, loss: 1381.33, mean loss: 0.12
--validation: 100%|██████████| 1631/1631 [02:21<00:00, 11.49it/s]
Post-processing 5349 example predictions split into 6523 features.
prediction: ['8.28', 'university of california,', 'itc', 'san diego', 'mr. ms.', '1128 sixteenth st., n. w., washington, d. c. 20036', 'an asset for the nation', 'the robert a. welch foundation', '11:14 to', '97500']
gold_answers: [['0.28'], ['university of california, san diego', 'university of california'], ['itc limited'], ['san diego'], ['paul'], ['1128 sixteenth st., n. w., washington, d. c. 20036'], ['aashirvaad'], ['the robert a. welch foundation'], ['11:14 to 11:39 a.m.', '11.14 to 11.39 a.m.'], ['$975.00', '975.00']]
[Info] Average Normalized Lev.S : 0.6143148732370792
Writing results to results/layoutlmv2-extractive-uncased.res.json and results/layoutlmv2-extractive-uncased.err.json
****Epoch Separation****
--training batch: 100%|██████████| 11092/11092 [52:03<00:00,  3.55it/s]
Finish epoch: 19, loss: 1323.24, mean loss: 0.12
--validation: 100%|██████████| 1631/1631 [02:21<00:00, 11.49it/s]
Post-processing 5349 example predictions split into 6523 features.
prediction: ['8.28', 'university of california,', 'itc', 'san diego', 'mr. ms.', '1128 sixteenth st., n. w., washington, d. c. 20036', 'an asset for the nation', 'the robert a. welch foundation', '11:14 to', '97500']
gold_answers: [['0.28'], ['university of california, san diego', 'university of california'], ['itc limited'], ['san diego'], ['paul'], ['1128 sixteenth st., n. w., washington, d. c. 20036'], ['aashirvaad'], ['the robert a. welch foundation'], ['11:14 to 11:39 a.m.', '11.14 to 11.39 a.m.'], ['$975.00', '975.00']]
[Info] Average Normalized Lev.S : 0.6152419536851927

**Comment by allanj** [comment]
I think you need to use the Microsoft API, which differs a lot.

I can see that you use the sliding window. My experience is that better to disable that because there is no improvement using sliding window.
Can you try that?

**Comment by roburst2** [comment]
Sure @allanj will try and share
Thanks for quick response

**Comment by roburst2** [comment]
After disabling sliding reached till 0.70. 
Next i am going to try with Microsoft API
